name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'categories:
  - title: 'ğŸ¥³ First Launch'
    label: 'firstLaunch'
  - title: 'ğŸš€ Features'
    label: 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    label: - 'bug'
  - title: 'ğŸ”¥ Hot Fixes'
    label: 'hotfix'
  - title: 'ğŸ“š Documentation'
    label: 'documentation'
  - title: 'ğŸ”³ ETC'
    label: 'etc'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## What's Changed $CHANGES ## Uncategorized